---
- name: get list of labels
  ansible.builtin.command: >-
    docker inspect
    --format {% raw %}'{{ range $key, $value := .Spec.Labels }}{{ printf "%s\n" $key }}{{ end }}'{% endraw %}
    {{ ansible_fqdn|lower }}
  register: docker_swarm_current_labels
  changed_when: false
  delegate_to: "{{ groups[docker_swarm_inventory_manager_group_name][0] }}"
  delegate_facts: true

- name: remove labels from swarm node
  ansible.builtin.command: docker node update --label-rm {{ item }} {{ ansible_fqdn|lower }}
  with_items: "{{ docker_swarm_current_labels.stdout_lines }}"
  when: item not in docker_swarm_labels
  delegate_to: "{{ groups[docker_swarm_inventory_manager_group_name][0] }}"
  delegate_facts: true

- name: assign labels to swarm nodes if any
  ansible.builtin.command: docker node update --label-add {{ item }}=true {{ ansible_fqdn|lower }}
  when: item not in docker_swarm_current_labels.stdout_lines
  with_items:
    - "{{ docker_swarm_labels | default([]) }}"
  delegate_to: "{{ groups[docker_swarm_inventory_manager_group_name][0] }}"
  delegate_facts: true
