---
- name: Remove workers nodes
  community.docker.docker_swarm:
    state: absent
    force: true
    node_id: "{{ inventory_hostname }}"
  when: inventory_hostname in groups[docker_swarm_inventory_worker_group_name]

- name: Remove managers nodes
  community.docker.docker_swarm:
    state: absent
    force: true
    node_id: "{{ inventory_hostname }}"
  when: >
        inventory_hostname in groups[docker_swarm_inventory_manager_group_name]
        and
        inventory_hostname not in groups[docker_swarm_inventory_manager_group_name][0]

- name: Remove first manager node
  community.docker.docker_swarm:
    state: absent
    force: true
    node_id: "{{ inventory_hostname }}"
  when: inventory_hostname in groups[docker_swarm_inventory_manager_group_name][0]

- name: Delete docker_gwbridge
  community.docker.docker_network:
    name: docker_gwbridge
    state: absent
    force: true

