---
- name: Setup roles
  become: true
  when: 
    - hostvars[item]['docker_swarm_node_role'] is defined
  delegate_to: "{{ groups[docker_swarm_inventory_manager_group_name][0] }}"
  loop: "{{ ansible_play_hosts | flatten }}"
  run_once: true
  community.docker.docker_node:
    hostname: "{{ item }}"
    docker_host: "{{ docker_swarm_node_docker_host | default('unix://var/run/docker.sock') }}"
    role: "{{ hostvars[item]['docker_swarm_node_role'] }}"
