---
- name: Setup availability
  become: true
  community.docker.docker_node:
    hostname: "{{ item }}"
    docker_host: "{{ docker_swarm_docker_host | default('unix://var/run/docker.sock') }}"
    availability: "{{ hostvars[item]['docker_swarm_availability'] | default('active') }}"
  delegate_to: "{{ groups[docker_swarm_inventory_manager_group_name][0] }}"
  loop: "{{ ansible_play_hosts | flatten }}"
  run_once: true
