---
- name: Enable swarm
  tags:
    - enable
  when:
  
    - docker_swarm_action == "enable"
  block:
    - name: Include tasks for setup bridge
      when:
        - docker_swarm_bridge_custom_subnet is defined
        - docker_swarm_bridge_custom_subnet | ansible.utils.ipv4
        - docker_swarm_bridge_custom_gw is defined
        - docker_swarm_bridge_custom_gw | ansible.utils.ipaddr
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup_bridge.yml

    - name: Include tasks for setup swarm
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup_swarm.yml

    - name: Include tasks for setup labels
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup_labels.yml

    - name: Include tasks for setup roles
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup_roles.yml

    - name: Include tasks for setup availability
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup_availability.yml

- name: Disable swarm
  tags:
    - disable
  when:
    - docker_swarm_action == "disable"
  block:
    - name: Include tasks for remove swarm
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/disable_swarm.yml
